### ISSUE TITLE
Does not work with utf-8 headers

### ISSUE THREAD

**Issue by brupxxxlgroup** [ApelegHQ/ts-multipart-parser#15]
Given the following simple HTTP multipart/form-data upload

<pre>
----------------------------695807392213189643524668
Content-Disposition: form-data; name="äasdasd"; filename="СЕРГЕЕНКО.rtf"; filename*=UTF-8''%D0%A1%D0%95%D0%A0%D0%93%D0%95%D0%95%D0%9D%D0%9A%D0%9E.rtf
Content-Type: application/rtf

{\rtf1}
----------------------------695807392213189643524668--
</pre>

the lib will fail with

<pre>
TypeError: Cannot convert argument to a ByteString because the character at index 38 has a value of 1057 which is greater than 255.
    at webidl.converters.ByteString (node:internal/deps/undici/undici:3661:17)
    at node:internal/deps/undici/undici:3550:20
    at Object.sequence<sequence<ByteString>> (node:internal/deps/undici/undici:3550:20)
    at webidl.converters.HeadersInit (node:internal/deps/undici/undici:8693:69)
    at new Headers (node:internal/deps/undici/undici:8523:36)
    at z (file:///C:/Repos/api.accountbalance.files.its/node_modules/@exact-realty/multipart-parser/dist/index.mjs:5:330)
    at v (file:///C:/Repos/api.accountbalance.files.its/node_modules/@exact-realty/multipart-parser/dist/index.mjs:6:903)
</pre>

What can be done about it? Thank you so much for your help.

**Comment by brupxxxlgroup** [comment]
[Can multipart parts have UTF-8 headers?](https://github.com/square/okhttp/issues/3876)

**Comment by brupxxxlgroup** [comment]
It seems the issue is here

https://github.com/ApelegHQ/ts-multipart-parser/blob/598fb44db61bd666d019688d91ab0478d27790c2/src/parseMessage.ts#L62

**Comment by corrideat** [comment]
Thank you for the report and the documentation. I'll take a look and see if / how this can be resolved.

It is my understanding that UTF-8 is generally not allowed in headers, although the link you provide seems to show that it's ambiguous.

If the issue is with the `Headers` constructor, then I'm not sure what the solution would be (I'd rather not implement a custom headers handler, if at all avoidable).

**Comment by corrideat** [comment]
Hi @brupxxxlgroup,

I was wondering if you could provide a reproducible way to test this. The examples provided are already useful, but I want to know how to get those payloads "in the wild".

Ideally, a simple HTML with inline JavaScript get results in different values in browsers would be useful. Save that, a list of steps to reproduce would be the next best.

Thanks,

**Comment by corrideat** [comment]
Hi @brupxxxlgroup 

Sorry that it took a while to get back to you. I believe this is solved now, by implementing your suggestion of adding a callback to parse headers. See `test/parseUnicodeHeaders.test.ts` for an example that just replaces Unicode characters with `.`.

This is fixed as of version `1.0.18`.
